### ISSUE TITLE
Isn't 0,0 bottom left?

### ISSUE THREAD

**Issue by 3d-gussner** [ff8jake/g81-to-heatmap#4]
Thanks for the great alternative to http://lokspace.eu/3d-printer-auto-bed-leveling-mesh-visualizer/

but isn't the 0,0 position in the bottom left corner?

**Comment by TheBrigandier** [comment]
Yes, but for some strange reason matplotlib defaults to placing the Y axis 0 at the top. The original "fix" for this to keep the zeros together was to move X labels at the top, but that also isn't very standard if you ask me and the title also had to be removed to do so.

I have adjusted things so that the mesh level output list gets reversed on Y axis before being handed off to numpy. This flips things upside down. I then flip it by Y axis again in the heatmap rendering settings, effectively moving 0 to the bottom and flipping things right side up again for the viewer.

Along with this, I have moved X labels back to the bottom and included the title again. Enjoy!
